### ISSUE TITLE
 warn: radar2.0 Promise failed Meldung im Log

### ISSUE THREAD

**Issue by MarkSau** [frankjoke/ioBroker.radar2#18]
Hatte heute den Js-Controller auf 1.5.9 eingespielt und bekomme jetzt die Meldung

2019-05-17 09:27:23.436 - warn: radar2.0 Promise failed @ '_tickCallback in internal/process/next_tick.js @68:7' error: { SyntaxError: Unexpected token c in JSON at position 0 at JSON.parse () at A.get.then.res (/opt/iobroker/node_modules/iobroker.radar2/radar2.js:621:47) at process._tickCallback (internal/process/next_tick.js:68:7) [stack]: 'SyntaxError: Unexpected token c in JSON at position 0\n at JSON.parse ()\n at A.get.then.res (/opt/iobroker/node_modules/iobroker.radar2/radar2.js:621:47)\n at process._tickCallback (internal/process/next_tick.js:68:7)', [message]: 'Unexpected token c in JSON at position 0' }

Was kann das denn sein?

UPDATE: Interessantes Verhalten. Habe im Adapter Debug aktiviert, Adapter neu gestartet und auch rebootet. Die Meldung erscheint nicht mehr... Werde jetzt Debug ausschalten und rebooten..mal sehn
UPDATE2: Meldung ist jetzt weg!? Strange...

**Comment by frankjoke** [comment]
Das scheint an deiner gelocation zu liegen die von UWZ nicht unterstützt wird. Schalt mal UWZ aus und schau obs dann noch da ist bw schau ob deine longitude/latitude richtig im iobroker admin eingetragen ist.

Wenns nicht mehr passiert dann kanns auch sein dass der Server von UWZ abwesend war.
