### ISSUE TITLE
Adapter not usable if no BT device

### ISSUE THREAD

**Issue by Garfonso** [frankjoke/ioBroker.radar2#34]
If there is no Bluetooth device installed in the system the adapter crashes and is not usable at all. Please consider to make Bluetooth optional (i.e. catch the error and ignore Bluetooth from then on in your code).

Log is as follows:
```
2020-02-13 11:34:32.021  - info: radar2.0 (4656) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v10.18.0
2020-02-13 11:34:32.147  - info: radar2.0 (4656) radar2 initialization started...
2020-02-13 11:34:32.228  - info: radar2.0 (4656) Connected with '0.0.0.0' for DHCP Scan
2020-02-13 11:34:32.315  - info: radar2.0 (4656) found '@abandonware/noble'
2020-02-13 11:34:32.316  - warn: radar2.0 (4656) node-bluetooth not found!
2020-02-13 11:34:32.316  - info: radar2.0 (4656) radar2 set to flag items away if they are not seen for 2 minutes
2020-02-13 11:34:32.317  - info: radar2.0 (4656) use known BT list: [ '01:12:23:34:45:56' ]
2020-02-13 11:34:32.317  - info: radar2.0 (4656) use known IP list: [ '1.1.1.1' ]
2020-02-13 11:34:32.317  - info: radar2.0 (4656) Remove name end for host names: .fritz.box
2020-02-13 11:34:32.318  - info: radar2.0 (4656) arp-scan will use the following interfaces: [ 'enp2s0' ]
2020-02-13 11:34:32.318  - info: radar2.0 (4656) radar2 set to scan every 20 seconds and printers every 720 minutes.
2020-02-13 11:34:32.327  - error: radar2.0 (4656) uncaught exception: ENODEV, No such device
2020-02-13 11:34:32.327  - error: radar2.0 (4656) Error: ENODEV, No such device
    at Hci.init (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js:101:35)
    at NobleBindings.init (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:82:13)
    at Noble.<anonymous> (/opt/iobroker/node_modules/@abandonware/noble/lib/noble.js:57:24)
    at process._tickCallback (internal/process/next_tick.js:61:11)
2020-02-13 11:34:32.328  - info: radar2.0 (4656) Adapter disconnected and stopped with dostop(false) and callback(true)
2020-02-13 11:34:38.162  - error: host.Server Caught by controller[0]: { Error: ENODEV, No such device
2020-02-13 11:34:38.162  - error: host.Server Caught by controller[0]:     at Hci.init (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js:101:35)
2020-02-13 11:34:38.162  - error: host.Server Caught by controller[0]:     at NobleBindings.init (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:82:13)
2020-02-13 11:34:38.162  - error: host.Server Caught by controller[0]:     at Noble.<anonymous> (/opt/iobroker/node_modules/@abandonware/noble/lib/noble.js:57:24)
2020-02-13 11:34:38.163  - error: host.Server Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:61:11) errno: 19, code: 'ENODEV', syscall: 'bind' }
2020-02-13 11:34:38.163  - info: host.Server instance system.adapter.radar2.0 terminated with code 0 (NO_ERROR)
2020-02-13 11:34:38.163  - info: host.Server Restart adapter system.adapter.radar2.0 because enabled

```

**Comment by jakolion** [comment]
I'm running ioBroker in a virtual machine without Bluetooth and getting the same error. That's why I cannot use this adapter. Please make Bluetooth optional - I would like to check for WiFi MAC addresses only.

**Comment by flaliqu** [comment]
same, it's desperate ... Please make Bluetooth optional

**Comment by frankjoke** [comment]
flaliqu, which version did you test? Version 2.0.1 has the flag to use hcitool instead of noble and it works without BT (I tested it on two systems without BT). Still, remove all BT macs from list! P.s.: please post such requests in iobroker forum on an existing  radar2 thread!
