### ISSUE TITLE
gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by MarkSau** [frankjoke/ioBroker.radar2#44]
Hi,

ich bekomme diesen Fehler, wenn ich einen beliebigen Adapter update:

2020-04-23 12:27:38.829 - info: host.MSNUC-IOB iobroker In file included from ../src/DeviceINQ.h:17, from ../src/linux/BluetoothSerialPort.cc:13:../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] , reinterpret_cast(AsyncExecuteComplete) ^
--
2020-04-23 12:27:38.877 - info: host.MSNUC-IOB iobroker ../src/linux/BluetoothSerialPort.cc: At global scope:../src/linux/BluetoothSerialPort.cc:18:14: error: variable or field ‘InitAll’ declared void void InitAll(Handle exports) { ^~~~~~../src/linux/BluetoothSerialPort.cc:18:14: error: ‘Handle’ was not declared in this scope
2020-04-23 12:27:38.881 - info: host.MSNUC-IOB iobroker ../src/linux/BluetoothSerialPort.cc:18:14: note: suggested alternative: ‘rand_r’ void InitAll(Handle exports) { ^~~~~~ rand_r../src/linux/BluetoothSerialPort.cc:18:27: error: expected primary-expression before ‘>’ token void InitAll(Handle exports) { ^
2020-04-23 12:27:38.882 - info: host.MSNUC-IOB iobroker ../src/linux/BluetoothSerialPort.cc:18:29: error: ‘exports’ was not declared in this scope void InitAll(Handle exports) { ^~~~~~~
2020-04-23 12:27:38.886 - info: host.MSNUC-IOB iobroker In file included from ../src/linux/BluetoothSerialPort.cc:12:../src/linux/BluetoothSerialPort.cc:23:34: error: ‘InitAll’ was not declared in this scope NODE_MODULE(BluetoothSerialPort, InitAll) ^~~~~~~/home/iobroker/.cache/node-gyp/12.16.2/include/node/node.h:608:36: note: in definition of macro ‘NODE_MODULE_X’ (node::addon_register_func) (regfunc), \ ^~~~~~~../src/linux/BluetoothSerialPort.cc:23:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(BluetoothSerialPort, InitAll) ^~~~~~~~~~~
2020-04-23 12:27:39.073 - info: host.MSNUC-IOB iobroker make: *** [BluetoothSerialPort.target.mk:117: Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o] Fehler 1
2020-04-23 12:27:39.077 - info: host.MSNUC-IOB iobroker gyp ERR! build error
2020-04-23 12:27:39.080 - info: host.MSNUC-IOB iobroker gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack at ChildProcess.emit (events.js:310:20)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)gyp ERR! System Linux 4.19.0-8-amd64gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"gyp ERR! cwd /opt/iobroker/node_modules/iobroker.radar2/node_modules/node-bluetoothgyp ERR! node -v v12.16.2gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok

**Comment by MarkSau** [comment]
Ich bin auf den Snapshot vor JS30 zurückgegangen und habe alles neu upgedated. JS30 Node12 und Radar 1.2.3...Fehler ist nun weg.
Möglicherweise hat ein Update der Zwischenversionen alles durcheinander geworfen.
Daher schliesse ich den Issue nun.
