### ISSUE TITLE
Cannot set property 'mtu' of undefined

### ISSUE THREAD

**Issue by Diginix** [frankjoke/ioBroker.radar2#50]
`
2020-05-04 13:00:36.819  - [31merror[39m: radar2.0 (419397) uncaught exception: Cannot set property 'mtu' of undefined
2020-05-04 13:00:36.822  - [31merror[39m: radar2.0 (419397) TypeError: Cannot set property 'mtu' of undefined
    at Noble.onMtu (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@abandonware/noble/lib/noble.js:564:18)
    at NobleBindings.emit (events.js:198:13)
    at NobleBindings.onMtu (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:277:8)
    at Gatt.emit (events.js:198:13)
    at Object._queueCommand [as callback] (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:329:10)
    at Gatt.onAclStreamData (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:133:26)
    at AclStream.emit (events.js:203:15)
    at AclStream.push (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@abandonware/noble/lib/hci-socket/acl-stream.js:33:10)
    at NobleBindings.onAclDataPkt (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:288:15)
    at Hci.emit (events.js:198:13)
`

adapter version 1.2.4
nodejs 10.20.1
JS-Controller 3.0.20

**Comment by frankjoke** [comment]
That's a noble problem, you may try to use hcitool instead or install node v12 where I did not get any of those noble errors.
